### ISSUE TITLE
SKATER File Corruption

### ISSUE THREAD

**Issue by devHazz** [devHazz/skate3-graphics-uploader#1]
The custom file writes currently corrupt the SKATER.P File. Possibility that IDs are not linking up correctly

**Comment by devHazz** [comment]
The bytes that are overwritten are all over the place. They'll either be in the correct offset, or have differences (by around a byte)

**Comment by devHazz** [comment]
Have attempted just writing to the body buffer, which works the same with less code but still ends up corrupted

**Comment by devHazz** [comment]
Will just attempt writing to RPCS3 memory and repeating the process there

**Comment by Ulfednyer** [comment]
Anything that is modified on the skater.p will break it sadly

**Comment by devHazz** [comment]
@Ulfednyer 
Yeah any functions that are currently writing to the SKATER.P file are currently deprecated so will be removed soon. Bit of a shame though eh.
